### ISSUE TITLE
HELPP my buttons are not working?????//??/??

### ISSUE THREAD

**Issue by 3096** [3096/ipswitch#3]
I'm too lazy to put a new release. Just use [this build](https://cdn.discordapp.com/attachments/477515660314935306/665747154974801961/ipswitch.nro ) for now

**Comment by theboy181** [comment]
Can you you update this, this caused me to format, and buy a new SD card. The HBC also is hosting the broken version. 

I assume this it a 9.1.0 specific issue?

**Comment by 3096** [comment]
Solved in 0.2.2
