### ISSUE TITLE
@nsobid - where to find in NSO?

### ISSUE THREAD

**Issue by GitGitHubUser** [3096/ipswitch#4]
Hello,
unfortunately you didn't specify where exactly to find nsobid used to identify the executed NSO. Can you please provide the information about it? Many thanks!

**Comment by 3096** [comment]
There are a few ways you could do that. My way of doing it is hactool: https://github.com/SciresM/hactool
use `hactool -t nso [your_nso_file]` will display the nsobid. Remove an even number of tailing zeros though. (or was it leading zeros? I forgot lol)
